# {final: [(initial, sandhied), ...], ...}
vowel_sandhi = {
        "a": [
                ("a", "A"),
                ("A", "A"),
                ("i", "e"),
                ("i", "e"),
                ("u", "o"),
                ("U", "o"),
                ("f", "ar"),
                ("e", "E"),
                ("E", "E"),
                ("o", "O"),
                ("O", "O")],
        "A": [
                ("a", "A"),
                ("A", "A"),
                ("i", "e"),
                ("i", "e"),
                ("u", "o"),
                ("U", "o"),
                ("f", "ar"),
                ("e", "E"),
                ("E", "E"),
                ("o", "O"),
                ("O", "O")],
        "i": [ # the application of these rules only when the form is not a dual has no incidence in the need to generate all sandhied forms here
                ("a", "ya"),
                ("A", "yA"),
                ("i", "I"),
                ("i", "I"),
                ("u", "yu"),
                ("U", "yU"),
                ("f", "yf"),
                ("e", "ye"),
                ("E", "yE"),
                ("o", "yo"),
                ("O", "yO")],
        "I": [ # idem
                ("a", "ya"),
                ("A", "yA"),
                ("i", "I"),
                ("i", "I"),
                ("u", "yu"),
                ("U", "yU"),
                ("f", "yf"),
                ("e", "ye"),
                ("E", "yE"),
                ("o", "yo"),
                ("O", "yO")],
        "u": [ # idem
                ("a", "va"),
                ("A", "vA"),
                ("i", "vi"),
                ("i", "vi"),
                ("u", "U"),
                ("U", "U"),
                ("f", "vf"),
                ("e", "ve"),
                ("E", "vE"),
                ("o", "vo"),
                ("O", "vO")],
        "U": [ # idem
                ("a", "va"),
                ("A", "vA"),
                ("i", "vi"),
                ("i", "vi"),
                ("u", "U"),
                ("U", "U"),
                ("f", "vf"),
                ("e", "ve"),
                ("E", "vE"),
                ("o", "vo"),
                ("O", "vO")],
        "f": [
                ("a", "ra"),
                ("A", "rA"),
                ("i", "ri"),
                ("i", "ri"),
                ("u", "ru"),
                ("U", "rU"),
                ("f", "F"),
                ("e", "re"),
                ("E", "rE"),
                ("o", "ro"),
                ("O", "rO")],
        "e": [
                ("a", "e '"),
                ("A", "a A"),
                ("i", "a i"),
                ("i", "a i"),
                ("u", "a u"),
                ("U", "a U"),
                ("f", "a f"),
                ("e", "a e"),
                ("E", "a E"),
                ("o", "a o"),
                ("O", "a O")],
        "E": [
                ("a", "A a"),
                ("A", "A A"),
                ("i", "A i"),
                ("i", "A i"),
                ("u", "A u"),
                ("U", "A U"),
                ("f", "A f"),
                ("e", "A e"),
                ("E", "A E"),
                ("o", "A o"),
                ("O", "A O")],
        "o": [
                ("a", "o '"),
                ("A", "avA"),
                ("i", "avi"),
                ("i", "avi"),
                ("u", "avu"),
                ("U", "avU"),
                ("f", "avf"),
                ("e", "ave"),
                ("E", "avE"),
                ("o", "avo"),
                ("O", "avO")],
        "O": [
                ("a", "Ava"),
                ("A", "AvA"),
                ("A", "A A"), # added to implement "Transformation to "a A" (loss of "v') is also acceptable"
                ("i", "Avi"),
                ("i", "Avi"),
                ("u", "Avu"),
                ("U", "AvU"),
                ("f", "Avf"),
                ("e", "Ave"),
                ("E", "AvE"),
                ("o", "Avo"),
                ("O", "AvO")],
            }

# {final: [(initial, (new_final, new_initial), context), ...], ...
consonant_sandhi_1 = {
        "k": [
            ("a", ("g", "a"), ""),
            ("A", ("g", "A"), ""),
            ("i", ("g", "i"), ""),
            ("i", ("g", "i"), ""),
            ("u", ("g", "u"), ""),
            ("U", ("g", "U"), ""),
            ("f", ("g", "f"), ""),
            ("e", ("g", "e"), ""),
            ("E", ("g", "E"), ""),
            ("o", ("g", "o"), ""),
            ("O", ("g", "O"), ""),
            ("y", ("g", "y"), ""),
            ("r", ("g", "r"), ""),
            ("l", ("g", "l"), ""),
            ("v", ("g", "v"), ""),
            ("S", ("g", "S"), ""),
            ("z", ("k", "z"), ""),
            ("s", ("k", "s"), ""),
            ("h", ("g", "G"), "")
        ],
        "w": [
            ("a", ("q", "a"), ""),
            ("A", ("q", "A"), ""),
            ("i", ("q", "i"), ""),
            ("i", ("q", "i"), ""),
            ("u", ("q", "u"), ""),
            ("U", ("q", "U"), ""),
            ("f", ("q", "f"), ""),
            ("e", ("q", "e"), ""),
            ("E", ("q", "E"), ""),
            ("o", ("q", "o"), ""),
            ("O", ("q", "O"), ""),
            ("y", ("q", "y"), ""),
            ("r", ("q", "r"), ""),
            ("l", ("q", "l"), ""),
            ("v", ("q", "v"), ""),
            ("S", ("w", "S"), ""),
            ("z", ("w", "z"), ""),
            ("s", ("w", "s"), ""),
            ("h", ("q", "Q"), "")
        ],
        "t": [
            ("a", ("d", "a"), ""),
            ("A", ("d", "A"), ""),
            ("i", ("d", "i"), ""),
            ("i", ("d", "i"), ""),
            ("u", ("d", "u"), ""),
            ("U", ("d", "U"), ""),
            ("f", ("d", "f"), ""),
            ("e", ("d", "e"), ""),
            ("E", ("d", "E"), ""),
            ("o", ("d", "o"), ""),
            ("O", ("d", "O"), ""),
            ("y", ("d", "y"), ""),
            ("r", ("d", "r"), ""),
            ("l", ("l", "l"), ""),
            ("v", ("d", "v"), ""),
            ("S", ("c", "C"), ""),
            ("z", ("t", "z"), ""),
            ("s", ("t", "s"), ""),
            ("h", ("d", "D"), "")
        ],
        "p": [
            ("a", ("b", "a"), ""),
            ("A", ("b", "A"), ""),
            ("i", ("b", "i"), ""),
            ("i", ("b", "i"), ""),
            ("u", ("b", "u"), ""),
            ("U", ("b", "U"), ""),
            ("f", ("b", "f"), ""),
            ("e", ("b", "e"), ""),
            ("E", ("b", "E"), ""),
            ("o", ("b", "o"), ""),
            ("O", ("b", "O"), ""),
            ("y", ("b", "y"), ""),
            ("r", ("b", "r"), ""),
            ("l", ("b", "l"), ""),
            ("v", ("b", "v"), ""),
            ("S", ("p", "S"), ""),
            ("z", ("p", "z"), ""),
            ("s", ("p", "s"), ""),
            ("h", ("b", "B"), "")
        ],
        "N": [
            ("a", ("NN", "a"), "previousVowel=a i u f x"),
            ("A", ("NN", "A"), "previousVowel=a i u f x"),
            ("i", ("NN", "i"), "previousVowel=a i u f x"),
            ("i", ("NN", "i"), "previousVowel=a i u f x"),
            ("u", ("NN", "u"), "previousVowel=a i u f x"),
            ("U", ("NN", "U"), "previousVowel=a i u f x"),
            ("f", ("NN", "f"), "previousVowel=a i u f x"),
            ("e", ("NN", "e"), "previousVowel=a i u f x"),
            ("E", ("NN", "E"), "previousVowel=a i u f x"),
            ("o", ("NN", "o"), "previousVowel=a i u f x"),
            ("O", ("NN", "O"), "previousVowel=a i u f x"),
            ("y", ("N", "y"), ""),
            ("r", ("N", "r"), ""),
            ("l", ("N", "l"), ""),
            ("v", ("N", "v"), ""),
            ("S", ("N", "S"), ""),
            ("z", ("N", "z"), ""),
            ("s", ("N", "s"), ""),
            ("h", ("N", "h"), "")
        ],
        "n": [
            ("a", ("nn", "a"), "previousVowel=a i u f x"),
            ("A", ("nn", "A"), "previousVowel=a i u f x"),
            ("i", ("nn", "i"), "previousVowel=a i u f x"),
            ("i", ("nn", "i"), "previousVowel=a i u f x"),
            ("u", ("nn", "u"), "previousVowel=a i u f x"),
            ("U", ("nn", "U"), "previousVowel=a i u f x"),
            ("f", ("nn", "f"), "previousVowel=a i u f x"),
            ("e", ("nn", "e"), "previousVowel=a i u f x"),
            ("E", ("nn", "E"), "previousVowel=a i u f x"),
            ("o", ("nn", "o"), "previousVowel=a i u f x"),
            ("O", ("nn", "O"), "previousVowel=a i u f x"),
            ("y", ("n", "y"), ""),
            ("r", ("n", "r"), ""),
            ("l", ("Ml", "l"), ""), # rendered as a chandrabindu in devanagari. changes nothing in the SLP1 we use here.
            ("v", ("n", "v"), ""),
            ("S", ("Y", "S"), ""), # both forms, this line and the next, are possible.
            ("S", ("Y", "C"), ""),
            ("z", ("n", "z"), ""),
            ("s", ("n", "s"), ""),
            ("h", ("n", "h"), "")
        ],
        "m": [
            ("a", ("m", "a"), ""),
            ("A", ("m", "A"), ""),
            ("i", ("m", "i"), ""),
            ("i", ("m", "i"), ""),
            ("u", ("m", "u"), ""),
            ("U", ("m", "U"), ""),
            ("f", ("m", "f"), ""),
            ("e", ("m", "e"), ""),
            ("E", ("m", "E"), ""),
            ("o", ("m", "o"), ""),
            ("O", ("m", "O"), ""),
            ("y", ("M", "y"), ""),
            ("r", ("M", "r"), ""),
            ("l", ("M", "l"), ""),
            ("v", ("M", "v"), ""),
            ("S", ("M", "S"), ""),
            ("z", ("M", "z"), ""),
            ("s", ("M", "s"), ""),
            ("h", ("M", "h"), "")
        ]
}